language: rust

rust:
  - stable
  - beta
  - nightly
 
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - rust: nightly
      script:
          - cargo build --verbose --all-features
          - cargo test --verbose --all-features

cache: cargo

script:
  - cargo build --verbose
  - cargo test --verbose
