[package]
name = "flatk"
version = "0.2.0"
authors = ["Egor Larionov <egor.larionov@gmail.com>"]
edition = "2018"

description = "Flat layout abstraction toolkit."
license = "MIT OR Apache-2.0"
readme = "README.md"

homepage = "https://github.com/elrnv/flatk"
repository = "https://github.com/elrnv/flatk"
documentation = "https://docs.rs/flatk"
keywords = ["chunked", "sparse", "entity", "structure", "layout"]

[dependencies]
typenum = "1.12.0"
reinterpret = "0.2.1"
rayon = { version = "1.3.1", optional = true }
packed_simd = { version = "0.3", optional = true }
flatk-derive = { path = "flatk-derive", optional = true }

[dev-dependencies]
rand = "0.7"
criterion = "0.3"

[features]
default = ["derive"]
unstable = ["criterion/real_blackbox", "packed_simd"]
derive = ["flatk-derive"]

[[bench]]
name = "storage"
harness = false

[[bench]]
name = "storage_ints"
harness = false

[[bench]]
name = "chunks_iter"
harness = false

[[bench]]
name = "zip"
harness = false
